name: CI/CD

on:
  push:
    branches: [ main2 ]
  pull_request:
    branches: [ main2 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: sonarscan-dotnet
      uses: highbyte/sonarscan-dotnet@v2.1.1-beta
      with:
        # The key of the SonarQube projects
        sonarProjectKey: 210628-UTA-NET_klaus-lawson-P1
        # The name of the SonarQube project
        sonarProjectName: AppStore
        sonarOrganization: 210628-uta-net
        dotnetDisableTests: true
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      run: dotnet publish --configuration Release -o ./publish
    - name: deploy
      uses: azure/webapps-deploy@v2
      with: 
        app-name: StoreAppConsole
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} 
        package: ./publish
# name: .NET

# on:
#   push:
#     branches: [ main2 ]
#   pull_request:
#     branches: [ main2 ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Setup .NET
#       uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: 5.0.x
#     - name: Restore dependencies
#       run: dotnet restore 
#     - name: Build
#       run: dotnet build  --configuration Release --no-restore
#     - name: Test
#       run: dotnet test CoreC#/RestaurantReview/ --no-build --verbosity normal
#     - name: Code Analysis
#       # You may pin to the exact commit or the version.
#       # uses: highbyte/sonarscan-dotnet@90025f8a91fb480278dbd6cf740ee9d862f7794c
#       uses: highbyte/sonarscan-dotnet@v2.1.1-beta
#       with:
#         # The key of the SonarQube projects
#         sonarProjectKey: 210628-UTA-NET_klaus-lawson-P1
#         # The name of the SonarQube project
#         sonarProjectName: AppStore
#         sonarOrganization: 210628-uta-net
#         dotnetDisableTests: true
#       env:
#         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#     - name: publish
#       run: dotnet publish --configuration Release -o ./publish
#     - name: deploy
#       uses: azure/webapps-deploy@v2
#       with: 
#         app-name: StoreAppConsole # Replace with your app name
#         publish-profile: ${{ secret.AZURE_WEBAPP_PUBLISH_PROFILE }} # Define secret variable in repository settings as per action documentation
#         package: ./publish
